# Generated by makeXDC.ulp developed by Sven Raiser, Tuebingen, Germany
#
# Board:     ESA11-7z030-V3.1.brd
# Part Name: FPGA
# Part pkg:  SBG485_OR_CLG485
# Created:   08.08.2016 17:08:02

#
#	Clock & Reset (33Mhz on PS)
#
#set_property -dict {PACKAGE_PIN F16 IOSTANDARD LVTTL} [get_ports 33.333MHZ]
set_property -dict {PACKAGE_PIN Y15 IOSTANDARD LVTTL} [get_ports i_100MHZ_N]
set_property -dict {PACKAGE_PIN Y14 IOSTANDARD LVTTL} [get_ports i_100MHZ_P]
#set_property -dict {PACKAGE_PIN B18 IOSTANDARD LVTTL} [get_ports PON_RESET_N]

#
#	UARTs (UART1 on PS)
#
#set_property -dict {PACKAGE_PIN L7 IOSTANDARD LVTTL} [get_ports UART1_CTS_N_1V8]
#set_property -dict {PACKAGE_PIN P8 IOSTANDARD LVTTL} [get_ports UART1_RTS_N_1V8]
#set_property -dict {PACKAGE_PIN M8 IOSTANDARD LVTTL} [get_ports UART1_RXD_1V8]
#set_property -dict {PACKAGE_PIN N8 IOSTANDARD LVTTL} [get_ports UART1_TXD_1V8]
#set_property -dict {PACKAGE_PIN R8 IOSTANDARD LVTTL} [get_ports UART2_CTS_N_1V8]
#set_property -dict {PACKAGE_PIN M7 IOSTANDARD LVTTL} [get_ports UART2_RTS_N_1V8]
#set_property -dict {PACKAGE_PIN R7 IOSTANDARD LVTTL} [get_ports UART2_RXD_1V8]
#set_property -dict {PACKAGE_PIN P6 IOSTANDARD LVTTL} [get_ports UART2_TXD_1V8]
#set_property -dict {PACKAGE_PIN C9 IOSTANDARD LVTTL} [get_ports UART3_RXD_1V8]
#set_property -dict {PACKAGE_PIN D12 IOSTANDARD LVTTL} [get_ports UART3_TXD_1V8]

#
#	LEDs
#
set_property -dict {PACKAGE_PIN G7 IOSTANDARD LVCMOS18} [get_ports {led[0]}]
set_property -dict {PACKAGE_PIN J6 IOSTANDARD LVCMOS18} [get_ports {led[1]}]
set_property -dict {PACKAGE_PIN V15 IOSTANDARD LVCMOS18} [get_ports {led[2]}]

#
#	Ethernet on PS
#
#set_property -dict {PACKAGE_PIN D13 IOSTANDARD LVTTL} [get_ports ETH_MDC]
#set_property -dict {PACKAGE_PIN C11 IOSTANDARD LVTTL} [get_ports ETH_MDIO]
#set_property -dict {PACKAGE_PIN A9 IOSTANDARD LVTTL} [get_ports ETH_RXCK]
#set_property -dict {PACKAGE_PIN D16 IOSTANDARD LVTTL} [get_ports ETH_RXCTL]
#set_property -dict {PACKAGE_PIN E12 IOSTANDARD LVTTL} [get_ports {ETH_RXD[0]}]
#set_property -dict {PACKAGE_PIN B16 IOSTANDARD LVTTL} [get_ports {ETH_RXD[1]}]
#set_property -dict {PACKAGE_PIN F11 IOSTANDARD LVTTL} [get_ports {ETH_RXD[2]}]
#set_property -dict {PACKAGE_PIN A10 IOSTANDARD LVTTL} [get_ports {ETH_RXD[3]}]
#set_property -dict {PACKAGE_PIN D17 IOSTANDARD LVTTL} [get_ports ETH_TXCK]
#set_property -dict {PACKAGE_PIN F12 IOSTANDARD LVTTL} [get_ports ETH_TXCTL]
#set_property -dict {PACKAGE_PIN E14 IOSTANDARD LVTTL} [get_ports {ETH_TXD[0]}]
#set_property -dict {PACKAGE_PIN A16 IOSTANDARD LVTTL} [get_ports {ETH_TXD[1]}]
#set_property -dict {PACKAGE_PIN E13 IOSTANDARD LVTTL} [get_ports {ETH_TXD[2]}]
#set_property -dict {PACKAGE_PIN A15 IOSTANDARD LVTTL} [get_ports {ETH_TXD[3]}]

#
#	EXPMODs
#
#set_property -dict {PACKAGE_PIN AA14 IOSTANDARD LVTTL} [get_ports {EXPMOD1[1]}]
#set_property -dict {PACKAGE_PIN AB12 IOSTANDARD LVTTL} [get_ports {EXPMOD1[2]}]
#set_property -dict {PACKAGE_PIN Y12 IOSTANDARD LVTTL} [get_ports {EXPMOD1[3]}]
#set_property -dict {PACKAGE_PIN AA12 IOSTANDARD LVTTL} [get_ports {EXPMOD1[4]}]
#set_property -dict {PACKAGE_PIN AB11 IOSTANDARD LVTTL} [get_ports {EXPMOD1[5]}]
#set_property -dict {PACKAGE_PIN AB13 IOSTANDARD LVTTL} [get_ports {EXPMOD1[6]}]
#set_property -dict {PACKAGE_PIN AA11 IOSTANDARD LVTTL} [get_ports {EXPMOD1[7]}]
#set_property -dict {PACKAGE_PIN AB14 IOSTANDARD LVTTL} [get_ports {EXPMOD1[8]}]
#set_property -dict {PACKAGE_PIN Y19 IOSTANDARD LVTTL} [get_ports {EXPMOD2[1]}]
#set_property -dict {PACKAGE_PIN V11 IOSTANDARD LVTTL} [get_ports {EXPMOD2[2]}]
#set_property -dict {PACKAGE_PIN W12 IOSTANDARD LVTTL} [get_ports {EXPMOD2[3]}]
#set_property -dict {PACKAGE_PIN W13 IOSTANDARD LVTTL} [get_ports {EXPMOD2[4]}]
#set_property -dict {PACKAGE_PIN U12 IOSTANDARD LVTTL} [get_ports {EXPMOD2[5]}]
#set_property -dict {PACKAGE_PIN V13 IOSTANDARD LVTTL} [get_ports {EXPMOD2[6]}]
#set_property -dict {PACKAGE_PIN W11 IOSTANDARD LVTTL} [get_ports {EXPMOD2[7]}]
#set_property -dict {PACKAGE_PIN W15 IOSTANDARD LVTTL} [get_ports {EXPMOD2[8]}]

#
#	QSPI on PS
#
#set_property -dict {PACKAGE_PIN A19 IOSTANDARD LVTTL} [get_ports QSPI_CLK]
#set_property -dict {PACKAGE_PIN A22 IOSTANDARD LVTTL} [get_ports QSPI_CS_N]
#set_property -dict {PACKAGE_PIN A21 IOSTANDARD LVTTL} [get_ports {QSPI_DQ[0]}]
#set_property -dict {PACKAGE_PIN F17 IOSTANDARD LVTTL} [get_ports {QSPI_DQ[1]}]
#set_property -dict {PACKAGE_PIN E19 IOSTANDARD LVTTL} [get_ports {QSPI_DQ[2]}]
#set_property -dict {PACKAGE_PIN A20 IOSTANDARD LVTTL} [get_ports {QSPI_DQ[3]}]

#
#	SD-Card SD_M on PS, SD_F on FPGA
#
#set_property -dict {PACKAGE_PIN T17 IOSTANDARD LVTTL} [get_ports SD_F_CDET_N]
#set_property -dict {PACKAGE_PIN U18 IOSTANDARD LVTTL} [get_ports SD_F_CMD]
#set_property -dict {PACKAGE_PIN U17 IOSTANDARD LVTTL} [get_ports {SD_F_D[0]}]
#set_property -dict {PACKAGE_PIN V16 IOSTANDARD LVTTL} [get_ports {SD_F_D[1]}]
#set_property -dict {PACKAGE_PIN V18 IOSTANDARD LVTTL} [get_ports {SD_F_D[2]}]
#set_property -dict {PACKAGE_PIN V19 IOSTANDARD LVTTL} [get_ports {SD_F_D[3]}]
#set_property -dict {PACKAGE_PIN W18 IOSTANDARD LVTTL} [get_ports SD_F_SCLK]

#set_property -dict {PACKAGE_PIN D11 IOSTANDARD LVTTL} [get_ports SD_M_CDET_N]
#set_property -dict {PACKAGE_PIN C15 IOSTANDARD LVTTL} [get_ports SD_M_CMD]
#set_property -dict {PACKAGE_PIN D15 IOSTANDARD LVTTL} [get_ports {SD_M_D[0]}]
#set_property -dict {PACKAGE_PIN B12 IOSTANDARD LVTTL} [get_ports {SD_M_D[1]}]
#set_property -dict {PACKAGE_PIN E10 IOSTANDARD LVTTL} [get_ports {SD_M_D[2]}]
#set_property -dict {PACKAGE_PIN B14 IOSTANDARD LVTTL} [get_ports {SD_M_D[3]}]
#set_property -dict {PACKAGE_PIN E9 IOSTANDARD LVTTL} [get_ports SD_M_SCLK]
#set_property -dict {PACKAGE_PIN B13 IOSTANDARD LVTTL} [get_ports SD_M_WPROT_N]

#
#	Displayport
#
set_property -dict {PACKAGE_PIN  V9 IOSTANDARD LVDS} [get_ports DP_135MHZ_N]
set_property -dict {PACKAGE_PIN  U9 IOSTANDARD LVDS} [get_ports DP_135MHZ_P]
set_property -dict {PACKAGE_PIN  R4 IOSTANDARD LVDS} [get_ports DP_AUX_N]
set_property -dict {PACKAGE_PIN  R5 IOSTANDARD LVDS} [get_ports DP_AUX_P]
set_property -dict {PACKAGE_PIN W16 IOSTANDARD LVCMOS18} [get_ports DP_HPD]
set_property -dict {PACKAGE_PIN AB3 IOSTANDARD LVDS} [get_ports {DP_LANE_N[0]}]
set_property -dict {PACKAGE_PIN AA3 IOSTANDARD LVDS} [get_ports {DP_LANE_P[0]}]
set_property -dict {PACKAGE_PIN  Y4 IOSTANDARD LVDS} [get_ports {DP_LANE_N[1]}]
set_property -dict {PACKAGE_PIN  W4 IOSTANDARD LVDS} [get_ports {DP_LANE_P[1]}]

#
#	USB type C onnector
#
#set_property -dict {PACKAGE_PIN V5 IOSTANDARD LVTTL} [get_ports USBC_135MHZ_N]
#set_property -dict {PACKAGE_PIN U5 IOSTANDARD LVTTL} [get_ports USBC_135MHZ_P]
#set_property -dict {PACKAGE_PIN AB9 IOSTANDARD LVTTL} [get_ports USBC_RX1_N]
#set_property -dict {PACKAGE_PIN AA9 IOSTANDARD LVTTL} [get_ports USBC_RX1_P]
#set_property -dict {PACKAGE_PIN Y6 IOSTANDARD LVTTL} [get_ports USBC_RX2_N]
#set_property -dict {PACKAGE_PIN W6 IOSTANDARD LVTTL} [get_ports USBC_RX2_P]
#set_property -dict {PACKAGE_PIN AB5 IOSTANDARD LVTTL} [get_ports USBC_TX1_N]
#set_property -dict {PACKAGE_PIN AA5 IOSTANDARD LVTTL} [get_ports USBC_TX1_P]
#set_property -dict {PACKAGE_PIN Y2 IOSTANDARD LVTTL} [get_ports USBC_TX2_N]
#set_property -dict {PACKAGE_PIN W2 IOSTANDARD LVTTL} [get_ports USBC_TX2_P]

#
#	USB on USB3340 on PS
#
#set_property -dict {PACKAGE_PIN A14 IOSTANDARD LVTTL} [get_ports USB_CLK]
#set_property -dict {PACKAGE_PIN C16 IOSTANDARD LVTTL} [get_ports {USB_D[0]}]
#set_property -dict {PACKAGE_PIN G11 IOSTANDARD LVTTL} [get_ports {USB_D[1]}]
#set_property -dict {PACKAGE_PIN B11 IOSTANDARD LVTTL} [get_ports {USB_D[2]}]
#set_property -dict {PACKAGE_PIN F9 IOSTANDARD LVTTL} [get_ports {USB_D[3]}]
#set_property -dict {PACKAGE_PIN A11 IOSTANDARD LVTTL} [get_ports {USB_D[4]}]
#set_property -dict {PACKAGE_PIN B9 IOSTANDARD LVTTL} [get_ports {USB_D[5]}]
#set_property -dict {PACKAGE_PIN F10 IOSTANDARD LVTTL} [get_ports {USB_D[6]}]
#set_property -dict {PACKAGE_PIN C10 IOSTANDARD LVTTL} [get_ports {USB_D[7]}]
#set_property -dict {PACKAGE_PIN E15 IOSTANDARD LVTTL} [get_ports USB_DIR]
#set_property -dict {PACKAGE_PIN F14 IOSTANDARD LVTTL} [get_ports USB_NXT]
#set_property -dict {PACKAGE_PIN AA17 IOSTANDARD LVTTL} [get_ports USB_OC]
#set_property -dict {PACKAGE_PIN A12 IOSTANDARD LVTTL} [get_ports USB_STP]

#
#	Digital Video
#
#set_property -dict {PACKAGE_PIN AA20 IOSTANDARD LVTTL} [get_ports VID_CLK_N]
#set_property -dict {PACKAGE_PIN AA19 IOSTANDARD LVTTL} [get_ports VID_CLK_P]
#set_property -dict {PACKAGE_PIN AB17 IOSTANDARD LVTTL} [get_ports VID_D0_N]
#set_property -dict {PACKAGE_PIN AB16 IOSTANDARD LVTTL} [get_ports VID_D0_P]
#set_property -dict {PACKAGE_PIN AB19 IOSTANDARD LVTTL} [get_ports VID_D1_N]
#set_property -dict {PACKAGE_PIN AB18 IOSTANDARD LVTTL} [get_ports VID_D1_P]
#set_property -dict {PACKAGE_PIN AB22 IOSTANDARD LVTTL} [get_ports VID_D2_N]
#set_property -dict {PACKAGE_PIN AB21 IOSTANDARD LVTTL} [get_ports VID_D2_P]
#set_property -dict {PACKAGE_PIN AA15 IOSTANDARD LVTTL} [get_ports VID_RSCL]
#set_property -dict {PACKAGE_PIN AA16 IOSTANDARD LVTTL} [get_ports VID_RSDA]

#
#	PS MIO Block
#
#set_property -dict {PACKAGE_PIN G17 IOSTANDARD LVTTL} [get_ports PS_MIO0]
#set_property -dict {PACKAGE_PIN D18 IOSTANDARD LVTTL} [get_ports PS_MIO7]
#set_property -dict {PACKAGE_PIN E18 IOSTANDARD LVTTL} [get_ports PS_MIO8]
#set_property -dict {PACKAGE_PIN C19 IOSTANDARD LVTTL} [get_ports PS_MIO9]
#set_property -dict {PACKAGE_PIN G16 IOSTANDARD LVTTL} [get_ports PS_MIO10]
#set_property -dict {PACKAGE_PIN B19 IOSTANDARD LVTTL} [get_ports PS_MIO11]
#set_property -dict {PACKAGE_PIN C18 IOSTANDARD LVTTL} [get_ports PS_MIO12]
#set_property -dict {PACKAGE_PIN A17 IOSTANDARD LVTTL} [get_ports PS_MIO13]
#set_property -dict {PACKAGE_PIN B17 IOSTANDARD LVTTL} [get_ports PS_MIO14]
#set_property -dict {PACKAGE_PIN E17 IOSTANDARD LVTTL} [get_ports PS_MIO15]
#set_property -dict {PACKAGE_PIN D10 IOSTANDARD LVTTL} [get_ports PS_MIO50]
#set_property -dict {PACKAGE_PIN C13 IOSTANDARD LVTTL} [get_ports PS_MIO51]

#
#	All Other
#

#set_property -dict {PACKAGE_PIN T10 IOSTANDARD LVTTL} [get_ports FPGA_DONE]
#set_property -dict {PACKAGE_PIN T8 IOSTANDARD LVTTL} [get_ports FPGA_INIT]
#set_property -dict {PACKAGE_PIN V10 IOSTANDARD LVTTL} [get_ports FPGA_PROG]
#set_property -dict {PACKAGE_PIN H11 IOSTANDARD LVTTL} [get_ports FPGA_TCK]
#set_property -dict {PACKAGE_PIN H9 IOSTANDARD LVTTL} [get_ports FPGA_TDI]
#set_property -dict {PACKAGE_PIN G9 IOSTANDARD LVTTL} [get_ports FPGA_TDO]
#set_property -dict {PACKAGE_PIN H10 IOSTANDARD LVTTL} [get_ports FPGA_TMS]


#set_property -dict {PACKAGE_PIN W3 IOSTANDARD LVTTL} [get_ports MGTVCCAUX]
#set_property -dict {PACKAGE_PIN C14 IOSTANDARD LVTTL} [get_ports N$55]
#set_property -dict {PACKAGE_PIN U7 IOSTANDARD LVTTL} [get_ports N$118]
#set_property -dict {PACKAGE_PIN M16 IOSTANDARD LVTTL} [get_ports N$190]
#set_property -dict {PACKAGE_PIN N16 IOSTANDARD LVTTL} [get_ports N$191]
#set_property -dict {PACKAGE_PIN F15 IOSTANDARD LVTTL} [get_ports VREF0V9]
#set_property -dict {PACKAGE_PIN H16 IOSTANDARD LVTTL} [get_ports VTTREF]
#set_property -dict {PACKAGE_PIN P16 IOSTANDARD LVTTL} [get_ports VTTREF]
